export const defaultGlobals = {
  speed: 1,
  targetHeight: 0,
  targetRadius: 88,
  eyeHeight: 38,
  eyeRadius: 69,
  eyeSpeed: 0.06,
  fieldOfView: 85,
  ambientRed: 0.22,
  ambientGreen: 0.25,
  ambientBlue: 0.39,
  fogPower: 14.5,
  fogMult: 1.66,
  fogOffset: 0.53,
  fogRed: 0.54,
  fogGreen: 0.86,
  fogBlue: 1.0,
};

export const defaultFish = {
  fishHeightRange: 1,
  fishHeight: 25,
  fishSpeed: 0.124,
  fishOffset: 0.52,
  fishXClock: 1,
  fishYClock: 0.556,
  fishZClock: 1,
  fishTailSpeed: 1,
};

export const defaultInnerConst = {
  refractionFudge: 3,
  eta: 1,
  tankColorFudge: 0.8,
};

export const optionDefinitions = [
  { id: "normalMaps", label: "Normal Maps", defaultValue: true },
  { id: "reflection", label: "Reflection", defaultValue: true },
  { id: "tank", label: "Tank", defaultValue: true },
  { id: "museum", label: "Museum", defaultValue: true },
  { id: "fog", label: "Fog", defaultValue: true },
  { id: "bubbles", label: "Bubbles", defaultValue: true },
  { id: "lightRays", label: "Light Rays", defaultValue: false },
  { id: "lasers", label: "Lasers", defaultValue: false },
];

export const fishCountPresets = [
  1, 100, 500, 1000, 5000, 10000, 15000, 20000, 25000, 30000,
];

export const viewPresets = [
  {
    name: "Inside (A)",
    globals: {
      targetHeight: 63.3,
      targetRadius: 91.6,
      eyeHeight: 7.5,
      eyeRadius: 13.2,
      eyeSpeed: 0.0258,
      fieldOfView: 82.699,
      ambientRed: 0.218,
      ambientGreen: 0.502,
      ambientBlue: 0.706,
      fogPower: 16.5,
      fogMult: 1.5,
      fogOffset: 0.738,
      fogRed: 0.338,
      fogGreen: 0.81,
      fogBlue: 1,
      refractionFudge: 3,
      eta: 1,
      tankColorFudge: 0.796,
    },
  },
  {
    name: "Outside (A)",
    globals: {
      targetHeight: 17.1,
      targetRadius: 69.2,
      eyeHeight: 59.1,
      eyeRadius: 124.4,
      eyeSpeed: 0.0258,
      fieldOfView: 56.923,
      ambientRed: 0.218,
      ambientGreen: 0.246,
      ambientBlue: 0.394,
      fogPower: 27.1,
      fogMult: 1.46,
      fogOffset: 0.53,
      fogRed: 0.382,
      fogGreen: 0.602,
      fogBlue: 1,
      refractionFudge: 3,
      eta: 1,
      tankColorFudge: 1,
    },
  },
  {
    name: "Inside (Original)",
    globals: {
      targetHeight: 0,
      targetRadius: 88,
      eyeHeight: 38,
      eyeRadius: 69,
      eyeSpeed: 0.0258,
      fieldOfView: 64,
      ambientRed: 0.218,
      ambientGreen: 0.246,
      ambientBlue: 0.394,
      fogPower: 16.5,
      fogMult: 1.5,
      fogOffset: 0.738,
      fogRed: 0.338,
      fogGreen: 0.81,
      fogBlue: 1,
      refractionFudge: 3,
      eta: 1,
      tankColorFudge: 0.796,
    },
  },
  {
    name: "Outside (Original)",
    globals: {
      targetHeight: 72,
      targetRadius: 73,
      eyeHeight: 3.9,
      eyeRadius: 120,
      eyeSpeed: 0.0258,
      fieldOfView: 74,
      ambientRed: 0.218,
      ambientGreen: 0.246,
      ambientBlue: 0.394,
      fogPower: 27.1,
      fogMult: 1.46,
      fogOffset: 0.53,
      fogRed: 0.382,
      fogGreen: 0.602,
      fogBlue: 1,
      refractionFudge: 3,
      eta: 1,
      tankColorFudge: 1,
    },
  },
  {
    name: "Center (LG)",
    globals: {
      targetHeight: 24,
      targetRadius: 73,
      eyeHeight: 24,
      eyeRadius: 0,
      eyeSpeed: 0.06,
      fieldOfView: 60,
      ambientRed: 0.22,
      ambientGreen: 0.25,
      ambientBlue: 0.39,
      fogPower: 14.5,
      fogMult: 1.3,
      fogOffset: 0.53,
      fogRed: 0.54,
      fogGreen: 0.86,
      fogBlue: 1,
      refractionFudge: 3,
      eta: 1,
      tankColorFudge: 0.8,
    },
  },
  {
    name: "Outside (LG)",
    globals: {
      targetHeight: 20,
      targetRadius: 127,
      eyeHeight: 39.9,
      eyeRadius: 124,
      eyeSpeed: 0.06,
      fieldOfView: 24,
      ambientRed: 0.22,
      ambientGreen: 0.25,
      ambientBlue: 0.39,
      fogPower: 27.1,
      fogMult: 1.2,
      fogOffset: 0.53,
      fogRed: 0.382,
      fogGreen: 0.602,
      fogBlue: 1,
      refractionFudge: 3,
      eta: 1,
      tankColorFudge: 1,
    },
  },
];

export const networkDefaults = {
  timeout: 3000,
  fovMult: 1.21,
  fovFudge: 1,
  offsetMult: 1,
};

export const aquariumConfig = {
  enableVR: true,
  aquariumRoot: "./",
};
